package mc.toolkitmc.macroengine.generator;

import mc.toolkitmc.macroengine.util.FileUtil;

import java.io.IOException;
import java.nio.file.Path;

/**
 * Generates a complete datapack scaffold with macroEngine integration.
 *
 * Output structure:
 *   <datapacksDir>/<name>/
 *     pack.mcmeta
 *     data/
 *       <namespace>/
 *         function/
 *           <tick_fn>.mcfunction
 *           <load_fn>.mcfunction
 *           ame/
 *             init.mcfunction          ← macroEngine boot helper
 *         tags/
 *           (empty – put custom tags here)
 *       minecraft/
 *         tags/
 *           function/
 *             tick.json
 *             load.json
 */
public final class DatapackGenerator {

    // pack_format 61 = 1.21.4, supported up to 94 (1.21.11)
    private static final int FORMAT_MIN = 61;
    private static final int FORMAT_MAX = 94;

    private DatapackGenerator() {}

    public static void generate(Path datapacksDir,
                                String name,
                                String namespace,
                                String tickFn,
                                String loadFn) throws IOException {
        Path root = datapacksDir.resolve(name);
        FileUtil.mkdirs(root);

        // ── pack.mcmeta ───────────────────────────────────────────────────────
        FileUtil.writeJson(root.resolve("pack.mcmeta"), packMeta(name));

        // ── data/<namespace>/function/ ─────────────────────────────────────────
        Path fnDir = root.resolve("data").resolve(namespace).resolve("function");
        FileUtil.mkdirs(fnDir);
        FileUtil.write(fnDir.resolve(tickFn + ".mcfunction"),  tickFunction(namespace, tickFn));
        FileUtil.write(fnDir.resolve(loadFn + ".mcfunction"),  loadFunction(namespace, loadFn, name));

        // ── AME helper (ame/ subdir) ───────────────────────────────────────────
        Path ameDir = fnDir.resolve("ame");
        FileUtil.mkdirs(ameDir);
        FileUtil.write(ameDir.resolve("init.mcfunction"), ameInit(namespace));

        // ── macro input/output storage init ───────────────────────────────────
        Path macroDir = fnDir.resolve("macro");
        FileUtil.mkdirs(macroDir);
        FileUtil.write(macroDir.resolve("run.mcfunction"),    macroRun(namespace));
        FileUtil.write(macroDir.resolve("dispatch.mcfunction"), macroDispatch(namespace));

        // ── data/minecraft/tags/function/ ──────────────────────────────────────
        Path tagFnDir = root.resolve("data").resolve("minecraft").resolve("tags").resolve("function");
        FileUtil.mkdirs(tagFnDir);
        FileUtil.writeJson(tagFnDir.resolve("tick.json"), tagJson(namespace + ":" + tickFn));
        FileUtil.writeJson(tagFnDir.resolve("load.json"), tagJson(namespace + ":" + loadFn));

        // ── README ─────────────────────────────────────────────────────────────
        FileUtil.write(root.resolve("README.md"), readme(name, namespace, tickFn, loadFn));
    }

    // ─────────────────────────────────────────────────────────────────────────
    // File content templates
    // ─────────────────────────────────────────────────────────────────────────

    private static String packMeta(String name) {
        return """
                {
                  "pack": {
                    "pack_format": %d,
                    "supported_formats": { "min_inclusive": %d, "max_inclusive": %d },
                    "description": "%s (generated by MacroEngine Fabric)"
                  }
                }
                """.formatted(FORMAT_MIN, FORMAT_MIN, FORMAT_MAX, name);
    }

    private static String tickFunction(String ns, String fn) {
        return """
                # %s:%s — Tick entry point
                # Generated by MacroEngine Fabric
                #
                # This function runs every game tick.
                # Add your per-tick logic below.
                # Example: check scoreboard triggers, update timers, etc.

                # -- Guard: only run when loaded --
                execute if score .ame_loaded %s_load matches 1 run function %s:macro/dispatch
                """.formatted(ns, fn, ns, ns);
    }

    private static String loadFunction(String ns, String fn, String packName) {
        return """
                # %s:%s — Load entry point
                # Generated by MacroEngine Fabric
                #
                # This function runs on /reload and server start.

                scoreboard objectives add %s_load dummy
                scoreboard objectives add %s_cooldown dummy
                scoreboard objectives add %s_trigger trigger

                # Mark pack as loaded
                scoreboard players set .ame_loaded %s_load 1

                # Initialize macro engine storage
                data modify storage %s:engine Root set value {}
                data modify storage %s:input  Root set value {}
                data modify storage %s:output Root set value {}

                tellraw @a {"text":"[%s] Loaded (MacroEngine Fabric)","color":"green"}
                function %s:ame/init
                """.formatted(ns, fn,
                ns, ns, ns, ns,
                ns, ns, ns,
                packName, ns);
    }

    private static String ameInit(String ns) {
        return """
                # %s:ame/init — macroEngine integration bootstrap
                # Called automatically on load.
                #
                # Set default values in engine storage:
                data modify storage %s:engine version set value "1.0.0"
                data modify storage %s:engine namespace set value "%s"
                data modify storage %s:engine debug set value 0b
                """.formatted(ns, ns, ns, ns, ns);
    }

    private static String macroRun(String ns) {
        return """
                # %s:macro/run — Execute a macro with arguments from storage
                # Usage: write args to %s:input Args{...} then call this function
                #
                # Advanced macro call pattern (requires pack_format >= 57):
                #   $function %s:$(fn_path) with storage %s:input Args
                #
                # Direct macro example (call via: function %s:macro/run with storage %s:input Args):
                $scoreboard players set $(target) %s_cooldown $(ticks)
                """.formatted(ns, ns, ns, ns, ns, ns, ns);
    }

    private static String macroDispatch(String ns) {
        return """
                # %s:macro/dispatch — Central macro dispatcher (runs every tick)
                # Route to module functions based on queued commands in engine storage.
                #
                # Pattern: check queue → pop first entry → call target → loop if queue non-empty
                #
                # Example routing (uncomment and adapt):
                # execute if data storage %s:engine Queue[0] run function %s:macro/dispatch_next

                # Placeholder — add your dispatch logic here
                """.formatted(ns, ns, ns);
    }

    private static String tagJson(String fnId) {
        return """
                {
                  "values": ["%s"]
                }
                """.formatted(fnId);
    }

    private static String readme(String name, String ns, String tick, String load) {
        return """
                # %s

                Generated by **MacroEngine Fabric** — ToolkitMC developer toolkit.

                ## Namespace
                `%s`

                ## Entry Points
                | Purpose | Function ID |
                |---------|-------------|
                | Tick    | `%s:%s` |
                | Load    | `%s:%s` |

                ## Macro Engine Integration

                ### Storage layout
                | Storage | Purpose |
                |---------|---------|
                | `%s:engine` | Internal state, queue, debug flags |
                | `%s:input`  | Macro call arguments (write before calling) |
                | `%s:output` | Results from macro executions |

                ### Calling a macro function
                ```mcfunction
                # 1. Write arguments to input storage
                data modify storage %s:input Args set value {target:"@s", ticks:20}
                # 2. Call the macro function with storage args
                function %s:macro/run with storage %s:input Args
                ```

                ### Modules
                Use `/macro-engine add <module> %s <function> <purpose>` to inject module templates.

                ## Activation
                ```
                /datapack enable "file/%s"
                /reload
                ```
                """.formatted(name, ns,
                ns, tick, ns, load,
                ns, ns, ns,
                ns, ns, ns,
                name, name);
    }
}
