package mc.toolkitmc.macroengine.generator;

import mc.toolkitmc.macroengine.util.FileUtil;

import java.io.IOException;
import java.nio.file.Path;

/**
 * Generates a resource pack scaffold.
 *
 * Output structure:
 *   <rpDir>/
 *     pack.mcmeta
 *     assets/
 *       <namespace>/
 *         textures/  (empty, ready for custom textures)
 *         models/    (empty, ready for item/block models)
 *         items/     (1.21.4+ item model directory)
 *         lang/
 *           en_us.json
 *         sounds.json
 *     README.md
 */
public final class ResourcePackGenerator {

    // Resource pack format 46 = 1.21.4, supports up to 55 (1.21.11 range)
    private static final int FORMAT_MIN = 46;
    private static final int FORMAT_MAX = 55;

    private ResourcePackGenerator() {}

    public static void generate(Path rpRoot, String name, String namespace) throws IOException {
        FileUtil.mkdirs(rpRoot);

        // ── pack.mcmeta ───────────────────────────────────────────────────────
        FileUtil.writeJson(rpRoot.resolve("pack.mcmeta"), packMeta(name));

        // ── assets/<namespace>/ ───────────────────────────────────────────────
        Path assets = rpRoot.resolve("assets").resolve(namespace);

        // textures/
        FileUtil.mkdirs(assets.resolve("textures").resolve("item"));
        FileUtil.mkdirs(assets.resolve("textures").resolve("block"));
        FileUtil.mkdirs(assets.resolve("textures").resolve("gui"));

        // models/ (legacy, still used for blocks)
        FileUtil.mkdirs(assets.resolve("models").resolve("item"));
        FileUtil.mkdirs(assets.resolve("models").resolve("block"));

        // items/ (1.21.4+ per-item model overrides)
        FileUtil.mkdirs(assets.resolve("items"));
        FileUtil.writeJson(assets.resolve("items").resolve("_example.json"), exampleItemModel(namespace));

        // lang/
        Path langDir = assets.resolve("lang");
        FileUtil.mkdirs(langDir);
        FileUtil.writeJson(langDir.resolve("en_us.json"), langJson(namespace));

        // sounds.json
        FileUtil.writeJson(assets.resolve("sounds.json"), soundsJson());

        // ── README ─────────────────────────────────────────────────────────────
        FileUtil.write(rpRoot.resolve("README.md"), readme(name, namespace));
    }

    // ─────────────────────────────────────────────────────────────────────────
    // File content templates
    // ─────────────────────────────────────────────────────────────────────────

    private static String packMeta(String name) {
        return """
                {
                  "pack": {
                    "pack_format": %d,
                    "supported_formats": { "min_inclusive": %d, "max_inclusive": %d },
                    "description": "%s resource pack (generated by MacroEngine Fabric)"
                  }
                }
                """.formatted(FORMAT_MIN, FORMAT_MIN, FORMAT_MAX, name);
    }

    private static String exampleItemModel(String ns) {
        return """
                {
                  "_comment": "1.21.4+ item model override. Rename this file to your item id (e.g. diamond_sword.json).",
                  "model": {
                    "type": "minecraft:model",
                    "model": "%s:item/example"
                  }
                }
                """.formatted(ns);
    }

    private static String langJson(String ns) {
        return """
                {
                  "item.%s.example": "Example Item",
                  "block.%s.example": "Example Block"
                }
                """.formatted(ns, ns);
    }

    private static String soundsJson() {
        return """
                {
                  "_comment": "Define custom sounds here. See https://minecraft.wiki/w/Sounds.json"
                }
                """;
    }

    private static String readme(String name, String ns) {
        return """
                # %s (Resource Pack)

                Generated by **MacroEngine Fabric** — ToolkitMC developer toolkit.

                ## Namespace
                `%s`

                ## Directory Layout
                ```
                assets/%s/
                  textures/
                    item/     ← custom item textures (16×16 PNG)
                    block/    ← custom block textures
                    gui/      ← HUD/screen textures
                  models/
                    item/     ← legacy item model JSON files
                    block/    ← block model JSON files
                  items/      ← 1.21.4+ item model overrides (one JSON per item id)
                  lang/
                    en_us.json
                  sounds.json
                ```

                ## Item Model Override (1.21.4+)
                Create `assets/%s/items/<item_id>.json`:
                ```json
                {
                  "model": {
                    "type": "minecraft:model",
                    "model": "%s:item/my_item"
                  }
                }
                ```

                ## Activation
                Place this folder in the server's `resource_packs/` directory,
                then add it to `server.properties`:
                ```
                resource-pack=<url-to-your-pack>
                ```
                Or distribute as a zip for client-side installation.
                """.formatted(name, ns, ns, ns, ns);
    }
}
